# Usage: KITCHEN_YAML=.kitchen.docker.yml bundle exec kitchen list
---
driver:
  name: dokken
  chef_version: 17.9.26
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken
  chef_license: accept-no-persist

verifier:
  name: inspec

platforms:
- name: centos-8
  driver:
    image: centos:8
    intermediate_instructions:
      - RUN dnf clean all
      # - RUN dnf install -y sudo # Centos 8 deprecated see https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/
    pid_one_command: /usr/lib/systemd/systemd

- name: fedora-40
  driver:
    image: fedora:40
    intermediate_instructions:
    - RUN dnf clean all
    - RUN dnf install -y sudo
    - RUN dnf install -y libxcrypt-compat
    - RUN dnf install -y systemd
    pid_one_command: /lib/systemd/systemd

- name: ubuntu-24.04
  driver:
    image: ubuntu:24.04
    pid_one_command: /usr/bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get -y update
      - RUN /usr/bin/apt install -y systemd
      - RUN /usr/bin/apt-get install sudo -y

suites:
- name: default
  run_list:
    - recipe[test]
