---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    authorization:
      sudo:
        users:
          - vagrant

platforms:
- name: centos-6
  transport:
    name: speedy_ssh
  driver_config:
    box:     opscode-centos-6.7

- name: centos-7
  transport:
    name: speedy_ssh
  driver_config:
    box:     criteo-centos-7.2-core

- name: windows-2012r2
  transport:
    name: winrm
    elevated: true
    elevated_username: System
    elevated_password: null
  driver_config:
    box: criteo-windows-2012r2-standard

suites:
<%= require 'erubis'; Erubis::Eruby.new(File.read('.kitchen_suites.yml')).evaluate %>
