# Rules defined there are of course debatable.
# If you want to modify them:
# - discuss this with sre-core members (r.veznaver for instance)
# - submit the change in the code_generator

AllCops:
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 180


Metrics/ModuleLength:
  Max: 20

Metrics/MethodLength:
  Max: 40

Style/VariableNumber:
  Enabled: false

Metrics/AbcSize:
  Max: 60

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Metrics/BlockLength:
  Max: 60
  Exclude:
    - spec/**/*

Style/StringLiterals:
  ConsistentQuotesInMultiline: true

Style/FormatString:
  EnforcedStyle: percent

Style/MultilineBlockChain:
  Enabled: false


Style/FileName:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/**/*

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - dc

Metrics/ClassLength:
  Enabled: false

Style/ClassVars:
  Enabled: false
