name             'choregraphie'
maintainer       'SRE-Core'
maintainer_email 'g.seux@criteo.com'
license          'Apache License'
description      'Allow to coordinate changes induced by chef'
long_description 'Installs/Configures choregraphie'
version          '0.4.0'
supports         'centos'
supports         'windows'
