# This file is auto-generated by the code_generator
#
# Cookbook Name:: choregraphie
# Spec:: default
#
# Copyright (c) 2016 The Authors, All Rights Reserved.

require 'spec_helper'

describe 'choregraphie::readme' do

  let(:readme_file) do
    File.join(File.dirname(__FILE__), '../../../README.md')
  end

  it 'exists' do
    expect(File.exists?(readme_file))
  end

  it 'is non empty' do
    expect(File.read(readme_file)).not_to be_empty
  end
end
